name: devsecops pipeline 
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gitleaks:
    name: scan for secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch full history so gitleaks can scan all commits in the push
          fetch-depth: 0
 
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Set to "true" to use a paid Gitleaks license
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}    
  mutation-test:
    runs-on: ubuntu-latest
    needs: gitleaks
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: mvn clean package
      - run: mvn org.pitest:pitest-maven:mutationCoverage
